on:
  push:
  workflow_dispatch:

name: 'Container Registry Deploymemt'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    - name: Log in with Azure

      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        enable-AzPSSession: true

    - name: 'Deploy Infrastructure'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: 'BicepModules'
        template: src/BicepRepository.bicep
        parameters: servicePrincipalId=${{ secrets.AZURE_SPN_OBJECTID }}
