on:
  push:
  workflow_dispatch:

name: 'Container Registry Deploymemt'

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
    - name: Log in with Azure

      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        enable-AzPSSession: true

    - name: 'Deploy Infrastructure'
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: 'BicepModules'
        template: src/BicepRepository.bicep
        parameters: servicePrincipalId=${{ secrets.AZURE_SPN_OBJECTID }}

    outputs:
      azureRegistryUrl: ${{ steps.deploy.outputs.azureRegistryUrl }}

  build-and-deploy-modules:
    runs-on: ubuntu-latest
    needs: [deploy_infrastructure]

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        enable-AzPSSession: true

    - name: Get Changed modules
      shell: pwsh
      run: |
        .github/scripts/getChangedFiles.ps1 -modulesDirectory '${{ github.workspace }}' -targetDirectory '${{ runner.temp }}/UpdatedModules'

    - name: Build modules
      shell: pwsh
      run: |
        .github/scripts/buildBicepFiles.ps1 -targetDirectory '${{ runner.temp }}/UpdatedModules'

    - name: Publish Modules
      shell: pwsh
      run: |
        .github/scripts/pushModulesToRegistry.ps1 -targetDirectory '${{ runner.temp }}/UpdatedModules' -registryServer ${{ needs.deploy_infrastructure.outputs.azureRegistryUrl }}
